### ISSUE TITLE
Reduce amount of (production) dependencies

### ISSUE THREAD

**Issue by felipecrs** [felipecrs/bindl#226]
We should make it easier for other projects to adopt it. One of the barriers is the amount of dependencies bindl brings. We can:

- [x] Drop dependency on decompress-xz by default: https://github.com/felipecrs/bindl/issues/217
- [ ] Switch from oclif to clipanion: https://github.com/felipecrs/bindl/issues/225

**Comment by felipecrs** [comment]
Closing in favor of #225

**Comment by XhmikosR** [comment]
You could probably switch from chalk to picocolors since it looks like it's already in your deps tree.

```
+-- bindl@5.6.4
| `-- cosmiconfig@9.0.0
|   `-- parse-json@5.2.0
|     `-- @babel/code-frame@7.27.1
|       `-- picocolors@1.1.1
```

**Comment by XhmikosR** [comment]
https://arve0.github.io/npm-download-size/#bindl@4.2.7
https://arve0.github.io/npm-download-size/#bindl@5.6.3
https://arve0.github.io/npm-download-size/#bindl@5.6.4

So, it'll be one less package too. Minor gain compared to the rest but still :)

**Comment by felipecrs** [comment]
Yeah. I explored nano-spawn already, and the main reason why I didn't choose it is because it does not support running a command line. It needs the command and args to be split.

I could probably use nano-spawn plus another dependency for converting a command line into command and args, though.

**Comment by XhmikosR** [comment]
Nice!

Might be worth looking at https://github.com/antonk52/lilconfig if it fits
your needs.
